export const employees = [
  {
    userName: "Manjit Singh",
    userId: "manjitsingh",
    userEmail: "manjit.singh@uaml.in",
    department: "marketing",
    jobPosition: "junior",
    isStatus: "active",
    isAdmin: false,
    isHead: true,
    password: "1234",
  },
  {
    userName: "Rakesh Verma",
    userId: "rakesh",
    userEmail: "rakes@uaml.in",
    department: "quality",
    jobPosition: "senior",
    isStatus: "active",
    isAdmin: true,
    isHead: false,
    password: "1234",
  },
  {
    userName: "Amit Sharma",
    userId: "amit.sharma",
    userEmail: "amit.sharma@uaml.in",
    department: "sales",
    jobPosition: "manager",
    isStatus: "active",
    isAdmin: false,
    isHead: true,
    password: "1234",
  },
  {
    userName: "Neha Gupta",
    userId: "neha.g",
    userEmail: "neha.g@uaml.in",
    department: "hiring",
    jobPosition: "senior",
    isStatus: "active",
    isAdmin: false,
    isHead: false,
    password: "1234",
  },
  {
    userName: "Vikram Patel",
    userId: "vikram.p",
    userEmail: "vikram.patel@uaml.in",
    department: "production",
    jobPosition: "manager",
    isStatus: "active",
    isAdmin: false,
    isHead: false,
    password: "1234",
  },
  {
    userName: "Pooja Mehta",
    userId: "pooja.mehta",
    userEmail: "pooja.mehta@uaml.in",
    department: "account",
    jobPosition: "senior",
    isStatus: "suspend",
    isAdmin: false,
    isHead: false,
    password: "1234",
  },
  {
    userName: "Sanjay Kumar",
    userId: "sanjay.k",
    userEmail: "sanjay.kumar@uaml.in",
    department: "",
    jobPosition: "ceo",
    isStatus: "active",
    isAdmin: true,
    isHead: true,
    password: "1234",
  },
  {
    userName: "Kavita Joshi",
    userId: "kavita.j",
    userEmail: "kavita.joshi@uaml.in",
    department: "purchase",
    jobPosition: "junior",
    isStatus: "deactive",
    isAdmin: false,
    isHead: false,
    password: "1234",
  },
];
